ikun-svelte/ikun-ui

docs/.vitepress/components/logo-animate/index.ts, docs/.vitepress/components/logo-animate/src/black.vue, docs/.vitepress/components/logo-animate/src/circle.vue, docs/.vitepress/components/logo-animate/src/grey.vue, docs/.vitepress/components/logo-animate/src/index.vue, docs/.vitepress/theme/index.ts, docs/index.md, docs/vite.config.ts
=> docs: added homepage logo animation

docs/components/KInput.md, docs/components/KSelect.md
fix: doc fix with issue-74
close: #74
=> fix: Fix the input component document suffix description error

README.md
=> docs: improve words

CONTRIBUTING.md, CONTRIBUTING.zh-CN.md
=> docs: contribution guide update.

components/Button/__test__/__snapshots__/button.spec.ts.snap, components/Button/__test__/button.spec.ts, components/Button/src/index.svelte, components/Notification/__test__/notification.spec.ts, docs/components/KButton.md, docs/example/button/isBorder.svelte, docs/example/button/size.svelte, preset/src/shortcuts/button.ts
Button add button size and isBorder
=> feat: Button add button size and isBorder

scripts/watch.js
it can watch utils & preset now
=> chore: update watch script

components/Switch/__test__/switch.spec.ts, components/Switch/src/index.svelte, components/Switch/src/types.d.ts, docs/components/KSwitch.md
使用 switch 的时候value 的typescript类型错误，看了下源码，想试着优化下逻辑
=> refactor: optimize switch

components/Popover/src/index.svelte, pnpm-lock.yaml
=> fix: fix popover automatic update is arrow rendering error

components/Input/__test__/input.spec.ts, components/Input/src/index.svelte
=> feat(KInput): expose compositionstart and compositionend events

components/Button/src/index.svelte
=> fix: set button props default value

components/Avatar/package.json, components/Backtop/package.json, components/Badge/package.json, components/Breadcrumb/package.json, components/BreadcrumbItem/package.json, components/Button/package.json, components/ButtonGroup/package.json, components/Checkbox/package.json, components/ClientOnly/package.json, components/Collapse/package.json, components/Drawer/package.json, components/EyeDropper/package.json, components/Icon/package.json, components/Input/package.json, components/Mask/package.json, components/Message/package.json, components/MessageBox/package.json, components/Modal/package.json, components/Notification/package.json, components/Popover/package.json, components/Radio/package.json, components/Select/package.json, components/Spin/package.json, components/Switch/package.json, components/Tag/package.json, components/Tooltip/package.json, docs/example/button/icon.svelte, package.json, scripts/comp-pkg-morph.ts, utils/package.json
The development environment does not use tsup to compile Components in order to speed up the dev startup speed.
=> perf: speed up dev start up time

components/Mask/src/index.svelte, scripts/play.js
=> fix: Fix flicker when mask is off

package.json, pnpm-lock.yaml
=> feat: lint only staged-files

components/Popover/src/index.svelte, package.json, preset/src/rules.ts, preset/src/shortcuts/popover.ts
=> style: Optimize popover component shadow

components/Icon/package.json, pnpm-lock.yaml
missing `clsx` in `Icon` component
=> fix: npm install clsx

docs/components/KLink.md, play/src/routes/+page.ts
- fix link attrs default value error
- add +page.ts in play
=> docs: fix link attrs default value error

preset/src/shortcuts/spin.ts
=> fix: Fixed the problem that the spin component rotation style error

components/Radio/src/index.svelte, preset/src/shortcuts/radio.ts
=> fix: Fixed the problem that the radio component style is missing

preset/src/shortcuts/alert.ts
=> fix: The color of the close button of the alert component is wrong

components/RadioGroup/src/index.svelte, docs/components/KRadio.md
- fix radio group words error
- rm done list
=> docs: fix radioGroup doc words error

components/Contextmenu/tsconfig.json, components/Ellipsis/tsconfig.json, components/Grid/tsconfig.json, components/Popconfirm/tsconfig.json, scripts/new-component.js
- new component script
- ContentMenu component
- Ellipsis component
- Grid component
- Popconfirm component
=> chore: refactor tsconfig

components/Tag/__test__/__snapshots__/tag.spec.ts.snap, components/Tag/src/index.svelte
=> fix: fixed the problem that the tag component icon style error

scripts/utils.js
Use `await` in the `for` loop so that the next execution will only begin after the last one has finished.
Using `Promise.allSettled` can be executed simultaneously.
On my device it takes about 3 minutes to execute `pnpm build`, the modified way using `Promise.allSettled` takes about 1 minute (results may vary by device hardware).
```js
// scripts/build.js
import { runTask } from './utils.js';
(async () => {
console.time('runTask');
await runTask('pnpm run build', 'components', 'build');
console.timeEnd('runTask');
})();
```
Imagine if more components are added in the future, the builder will take longer and longer.
=> perf: increase build speed

scripts/utils.js
I thought that influx of a large number of asynchronous threads at the same time might cause side effects, so I added a simple version of the limit function that controls the number of concurrencies.
=> perf: control the number of concurrencies

play/src/app.css, play/src/routes/+layout.svelte, play/src/routes/+layout.ts
- added play layout
- play support toggle theme
=> feat: added play layout and support toggle theme

components/Switch/__test__/__snapshots__/switch.spec.ts.snap, components/Switch/__test__/switch.spec.ts, components/Switch/src/index.svelte, components/Switch/src/types.d.ts, docs/components/KSwitch.md, docs/example/switch/sizes.svelte, preset/src/shortcuts/src/swtich.ts
- added switch three sizes
- added switch test unit 
- added switch doc
=> feat: added switch three sizes

preset/src/shortcuts/src/input.ts
=> fix: fixed the smallest size input box has abnormal style in dark mode

CONTRIBUTING.md
=> docs: fix grammar mistakes

preset/src/shortcuts/src/input.ts, preset/src/shortcuts/src/select.ts
=> fix: input and select component bg should be transparent

components/Flex/__test__/__snapshots__/flex.spec.ts.snap, components/Flex/__test__/flex.spec.ts, components/Flex/package.json, components/Flex/src/index.svelte, components/Flex/src/index.ts, components/Flex/src/types.d.ts, components/Flex/tsconfig.json, components/index.ts, package.json, pnpm-lock.yaml, preset/src/shortcuts/index.ts, preset/src/shortcuts/src/flex.ts
=> feat: added KFlex component

components/Timeline/__test__/__snapshots__/timeline.spec.ts.snap, components/Timeline/__test__/timeline.spec.ts, components/Timeline/package.json, components/Timeline/src/index.svelte, components/Timeline/src/index.ts, components/Timeline/src/types.d.ts, components/Timeline/tsconfig.json, components/index.ts, package.json, pnpm-lock.yaml, preset/src/rules/index.ts, preset/src/rules/src/timeline.ts, preset/src/shortcuts/index.ts, preset/src/shortcuts/src/common.ts, preset/src/shortcuts/src/timeline.ts
=> feat: added timeline component
